
class PassowrdError(Exception):
    pass

class ProtectedError(Exception):
    pass